apiVersion: v1
kind: Service
metadata:
  name: rag-retail-agent-service
spec:
  type: NodePort
  selector:
    app: rag-retail-agent
  ports:
    - port: 80
      targetPort: 8000
      nodePort: 30080
